### PR TITLE
FsSpreadsheet.Exceljs

### PR DESCRIPTION
**Pull request by Freymaurer**
Hey have a look at this!

Current state is tracked here #41

### CODE REVIEW

**Review by omaus — APPROVED** [review]

**Comment by Freymaurer** [comment]
Please review, merge and release! ❤️ @omaus

**Comment by omaus** [comment]
Could you pls fix the errors/tests first?

**Comment by Freymaurer** [comment]
@omaus 👍

**Review by omaus — APPROVED** [review]
lgtm

**Pull request merged**
